//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.RewardAndRecognition {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Apps.RewardAndRecognition.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is your new admin!.
        /// </summary>
        public static string AdminHeaderText {
            get {
                return ResourceManager.GetString("AdminHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **{0}**({1}) has been set as R&amp;R Admin..
        /// </summary>
        public static string AdminName {
            get {
                return ResourceManager.GetString("AdminName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin selection.
        /// </summary>
        public static string AdminSubheaderText {
            get {
                return ResourceManager.GetString("AdminSubheaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already endorsed this nomination. We know that waiting is always the hardest part, but results should be out by {0}..
        /// </summary>
        public static string AlreadyendorsedMessage {
            get {
                return ResourceManager.GetString("AlreadyendorsedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are the winners!.
        /// </summary>
        public static string AwardWinnerCardTitle {
            get {
                return ResourceManager.GetString("AwardWinnerCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure R&amp;R admin.
        /// </summary>
        public static string ConfigureAdminTitle {
            get {
                return ResourceManager.GetString("ConfigureAdminTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to get started? Configure R&amp;R Admin..
        /// </summary>
        public static string ContentText {
            get {
                return ResourceManager.GetString("ContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This reward cycle is closed..
        /// </summary>
        public static string CycleClosedMessage {
            get {
                return ResourceManager.GetString("CycleClosedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no active reward cycle going on currently for the team. Please wait for sometime until the reward cycle has been set from admin..
        /// </summary>
        public static string CycleValidationMessage {
            get {
                return ResourceManager.GetString("CycleValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endorse.
        /// </summary>
        public static string EndorseButtonText {
            get {
                return ResourceManager.GetString("EndorseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endorsed by.
        /// </summary>
        public static string EndorsedByTableHeaderText {
            get {
                return ResourceManager.GetString("EndorsedByTableHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endorse.
        /// </summary>
        public static string EndorseTitle {
            get {
                return ResourceManager.GetString("EndorseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. please try again later.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Bot is not installed in the team..
        /// </summary>
        public static string InvalidTeamText {
            get {
                return ResourceManager.GetString("InvalidTeamText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Manage awards.
        /// </summary>
        public static string ManageAwardsBulletPoint {
            get {
                return ResourceManager.GetString("ManageAwardsBulletPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Go to RnR tab.
        /// </summary>
        public static string ManageRewardTitle {
            get {
                return ResourceManager.GetString("ManageRewardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey {0} way to go! - {1}..
        /// </summary>
        public static string MentionText {
            get {
                return ResourceManager.GetString("MentionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Nominate.
        /// </summary>
        public static string NominateBulletPoint {
            get {
                return ResourceManager.GetString("NominateBulletPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominate.
        /// </summary>
        public static string NominateButton {
            get {
                return ResourceManager.GetString("NominateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominate now.
        /// </summary>
        public static string NominateButtonText {
            get {
                return ResourceManager.GetString("NominateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominated by {0}..
        /// </summary>
        public static string NominatedByText {
            get {
                return ResourceManager.GetString("NominatedByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominate people.
        /// </summary>
        public static string NominatePeopleTitle {
            get {
                return ResourceManager.GetString("NominatePeopleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Note from team manager:** {0}.
        /// </summary>
        public static string NoteForTeamText {
            get {
                return ResourceManager.GetString("NoteForTeamText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OkButtonText {
            get {
                return ResourceManager.GetString("OkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish result.
        /// </summary>
        public static string PublishAwardButtonText {
            get {
                return ResourceManager.GetString("PublishAwardButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish result.
        /// </summary>
        public static string PublishAwardResultButtonText {
            get {
                return ResourceManager.GetString("PublishAwardResultButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward cycle has been configured from **{0}**  to **{1}**..
        /// </summary>
        public static string RewardCycleHeader {
            get {
                return ResourceManager.GetString("RewardCycleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward cycle:.
        /// </summary>
        public static string RewardCycleText {
            get {
                return ResourceManager.GetString("RewardCycleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s reward time!.
        /// </summary>
        public static string RewardTitle {
            get {
                return ResourceManager.GetString("RewardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Configure R&amp;R Admin.
        /// </summary>
        public static string SetAdminBulletPoint {
            get {
                return ResourceManager.GetString("SetAdminBulletPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure R&amp;R Admin.
        /// </summary>
        public static string SetAdminButtonText {
            get {
                return ResourceManager.GetString("SetAdminButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Set reward cycle.
        /// </summary>
        public static string SetRewardCycleBulletPoint {
            get {
                return ResourceManager.GetString("SetRewardCycleBulletPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks! You’ve successfully endorsed **{0}** for **{1}**. Results will be published on **{2}** ..
        /// </summary>
        public static string SuccessfulEndorseMessage {
            get {
                return ResourceManager.GetString("SuccessfulEndorseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently not supporting any bot command..
        /// </summary>
        public static string UnsupportedBotCommand {
            get {
                return ResourceManager.GetString("UnsupportedBotCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string WelcomeCardTitle {
            get {
                return ResourceManager.GetString("WelcomeCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are some of the things that I can do:.
        /// </summary>
        public static string WelcomeSubHeaderText {
            get {
                return ResourceManager.GetString("WelcomeSubHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, I am Rewards &amp; Recognition bot and I can help you nominate your team members for performance awards..
        /// </summary>
        public static string WelcomeTeamCardContent {
            get {
                return ResourceManager.GetString("WelcomeTeamCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the reward cycle.
        /// </summary>
        public static string WinnerCardRewardCycleTitle {
            get {
                return ResourceManager.GetString("WinnerCardRewardCycleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winners.
        /// </summary>
        public static string WinnersCountText {
            get {
                return ResourceManager.GetString("WinnersCountText", resourceCulture);
            }
        }
    }
}
